// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnnualCalcController from "./annual_calc_controller"
application.register("annual-calc", AnnualCalcController)

import DisplayResultController from "./display_result_controller"
application.register("display-result", DisplayResultController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItemCompController from "./item_comp_controller"
application.register("item-comp", ItemCompController)

import SourceFlipController from "./source_flip_controller"
application.register("source-flip", SourceFlipController)
